### ISSUE TITLE
Section on call, apply and bind

### ISSUE THREAD

**Issue by peterjwest** [BonsaiDen/JavaScript-Garden#260]
I thought it might be good to add a section on call, apply and bind. These aren't covered explicitly anywhere, and have some unusual behaviour. 

For example `bind` doesn't create a new function with bound arguments, it permanently binds arguments on that function, meaning future calls (or uses of bind) have no effect on those arguments.

**Comment by timruffles** [comment]
@peterjwest did you want to add this? Reopen if you do!

**Comment by peterjwest** [comment]
I don't think I'll have time anytime soon, so will leave this.

**Comment by lewisje** [comment]
It wasn't mentioned here, but although using `bind` on a bound function will not change the context on the original unbound function, it is still possible to partially apply more arguments:

    var a = console.log.bind(console, 'lol');
    a('rofl'); //=> lol rofl
    var b = a.bind(null, 'omg');
    b('wtf'); //=> lol omg wtf

(Also, likely because of scoping issues, the original unbound function cannot be accessed from a bound function.)
