### ISSUE TITLE
Issue with function evaluation

### ISSUE THREAD

**Issue by lor3k** [BonsaiDen/JavaScript-Garden#377]
`!function(){}()` does not evaluate the function expression

`!function(){return 5}()
/* false */`

In
> Scopes and Namespaces

**Comment by peterjwest** [comment]
You're confusing "evaluate" with "return".

See this example: `!function(){ console.log(1 + 1) }()`
If you run this, you'll see the code is evaluated because `2` will be logged to the console.
False is returned because the `!` is negating the output of the function.

This technique is only useful when you don't care about the return value of a function.
